INSERT INTO film (id, title, duration, director, summary, genre, rating, image, trailer_url) VALUES (1, 'Escape from Alcatraz', 112, 'Don Siegel', 'The true story of Frank Morris, a cunning bank robber who was sent to Alcatraz Island, the most feared prison in the world. Although nobody had ever escaped from Alcatraz, Frank masterminded this elaborately detailed and, as far as anyone knows, ultimately successful escape. In 29 years, this seemingly impenetrable federal penitentiary, which housed Al Capone and "Birdman" Robert Stroud, was only broken once by three inmates never heard of again.', 0, 8, 'plfvijivj', 'https://www.youtube.com/embed/UT4kc5jG990');
INSERT INTO actor (id, name, bio, birth_day, gender, profile_image) VALUES (1, 'Clint Eastwood', 'Clinton "Clint" Eastwood, Jr. (born May 31, 1930) is an American actor, film director, producer, musician, and politician. He rose to international fame with his role as the Man with No Name in Sergio Leone\'s Dollars trilogy of spaghetti Westerns during the 1960s, and as antihero cop Harry Callahan in the five Dirty Harry films throughout the 1970s and 1980s. These roles, among others, have made him an enduring cultural icon of masculinity.', '1930-05-31',  0, 'http://www.showbiz411.com/wp-content/uploads/2013/02/clint-eastwood.jpg');
INSERT INTO actor (id, name, bio, birth_day, gender, profile_image) VALUES (2, 'Roberts Blossom', 'Roberts Scott Blossom was born in 1924 in New Haven, Connecticut to John Blossom, an athletic director at Yale University. He was raised in Cleveland but later moved to Shaker Heights, Ohio. He attended Hawken School and graduated from Asheville School in 1941 and attended Harvard University for a year until he joined the Army and served in World War II in Europe. He trained as a therapist and later decided to be an actor, and began directing and acting in productions at Karamu House and the Candlelight Theater in Cleveland and later moved to New York, where he supported himself by bundling feathers for hats and he practiced a disputed therapy called Dianetics.', '1924-03-24', 0, 'http://media.sdreader.com/img/blogs/entry_img/2011/Jul/14/roberts_blossom1_t620.jpg');
INSERT INTO film_character (id, character_name, actor_id, film_id) VALUES (1, 'Frank Morris', 1, 1);
INSERT INTO film_character (id, character_name, actor_id, film_id) VALUES (2, 'Doc', 2, 1);






