INSERT INTO film (id, title, duration, director, summary, genre, rating, trailer_url, image) VALUES (1, 'Escape from Alcatraz', 112, 'Don Siegel', 'The true story of Frank Morris, a cunning bank robber who was sent to Alcatraz Island, the most feared prison in the world. Although nobody had ever escaped from Alcatraz, Frank masterminded this elaborately detailed and, as far as anyone knows, ultimately successful escape. In 29 years, this seemingly impenetrable federal penitentiary, which housed Al Capone and "Birdman" Robert Stroud, was only broken once by three inmates never heard of again.', 0, 8, 'https://www.youtube.com/embed/UT4kc5jG990', 'http://www.gstatic.com/tv/thumb/movieposters/3635/p3635_p_v7_aa.jpg');
INSERT INTO film (id, title, duration, director, summary, genre, rating, trailer_url, image) VALUES (2, 'True lies', 141, 'James Cameron', 'Harry Tasker: devoted father, husband, and computer salesman. Or so everyone thinks. In reality, Tasker is a spy in one of the United States government\'s highest branches. As Tasker continues to keep his profession a secret from his family, his wife, Helen, begins to surreptitiously meet with a used car salesman, Simon. Upon discovering this, Tasker sets out on a personal mission to win his wife back and find out Simon\'s true motives. Meanwhile, a Middle Eastern terrorist organization known as "Crimson Jihad" is on the rise, threatening nuclear war with the United States if their demands are not met. As the clock winds down, Tasker must not only fight against the bloodthirsty terrorists, but also fight to regain the trust of his family.', 1, 9.1, 'https://www.youtube.com/embed/3B7HG8_xbDw', 'http://t2.gstatic.com/images?q=tbn:ANd9GcSwsBywFdF5JJdega2zTOHY8QcpiZmF1sSbTKrOwc4jJBn3dFGS');

INSERT INTO actor (id, name, bio, birth_day, gender, profile_image) VALUES (1, 'Clint Eastwood', 'Clinton "Clint" Eastwood, Jr. (born May 31, 1930) is an American actor, film director, producer, musician, and politician. He rose to international fame with his role as the Man with No Name in Sergio Leone\'s Dollars trilogy of spaghetti Westerns during the 1960s, and as antihero cop Harry Callahan in the five Dirty Harry films throughout the 1970s and 1980s. These roles, among others, have made him an enduring cultural icon of masculinity.', '1930-05-31',  0, 'http://www.showbiz411.com/wp-content/uploads/2013/02/clint-eastwood.jpg');
INSERT INTO actor (id, name, bio, birth_day, gender, profile_image) VALUES (2, 'Roberts Blossom', 'Roberts Scott Blossom was born in 1924 in New Haven, Connecticut to John Blossom, an athletic director at Yale University. He was raised in Cleveland but later moved to Shaker Heights, Ohio. He attended Hawken School and graduated from Asheville School in 1941 and attended Harvard University for a year until he joined the Army and served in World War II in Europe. He trained as a therapist and later decided to be an actor, and began directing and acting in productions at Karamu House and the Candlelight Theater in Cleveland and later moved to New York, where he supported himself by bundling feathers for hats and he practiced a disputed therapy called Dianetics.', '1924-03-24', 0, 'http://media.sdreader.com/img/blogs/entry_img/2011/Jul/14/roberts_blossom1_t620.jpg');
INSERT INTO actor (id, name, bio, birth_day, gender, profile_image) VALUES (3, 'Arnold Schwarzenegger', 'Arnold Alois Schwarzenegger, born July 30, 1947) is an Austrian-born American actor, model, producer, director, activist, businessman, investor, writer, philanthropist, former professional bodybuilder, and politician. Schwarzenegger served two terms as the 38th Governor of California from 2003 until 2011. Schwarzenegger began weight training at the age of 15. He won the Mr. Universe title at age 20 and went on to win the Mr. Olympia contest seven times. Schwarzenegger has remained a prominent presence in bodybuilding and has written many books and articles on the sport. Schwarzenegger gained worldwide fame as a Hollywood action film icon. Schwarzenegger\'s breakthrough film was the sword-and-sorcery epic Conan the Barbarian in 1982, which was a box-office hit and resulted in a sequel. In 1984, he appeared in James Cameron\'s science-fiction thriller film The Terminator, which was a massive critical and box-office success. Schwarzenegger subsequently reprised the Terminator character in the franchise\'s later installments in 1991, 2003, and 2015. He appeared in a number of successful films, such as Commando (1985, The Running Man (1987), Predator (1987), Twins (1988), Total Recall (1990), Kindergarten Cop (1990) and True Lies (1994). He was nicknamed the "Austrian Oak" and the "Styrian Oak" in his bodybuilding days, "Arnie" during his acting career, and "The Governator" (a portmanteau of "Governor" and "The Terminator" – one of his best-known movie roles) since the start of his political career.', '1947-07-30', 0, 'http://upload.wikimedia.org/wikipedia/commons/3/33/Arnold_Schwarzenegger_edit(ws).jpg');

INSERT INTO film_character (id, character_name, actor_id, film_id) VALUES (1, 'Frank Morris', 1, 1);
INSERT INTO film_character (id, character_name, actor_id, film_id) VALUES (2, 'Doc', 2, 1);
INSERT INTO film_character (id, character_name, actor_id, film_id) VALUES (3, 'Harry Tasker', 3, 2);







